# Generated by Django 5.1.2 on 2024-11-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chat_id',
            new_name='telegram_chat_id',
        ),
    ]
