# Generated by Django 5.1.2 on 2024-11-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_habit_execution_interval_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна/Не активна"),
        ),
    ]
