# Generated by Django 5.1.2 on 2024-11-02 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.CharField(choices=[('O', 'Открытая привычка'), ('P', 'Приватная привычка')], default='P', max_length=1, verbose_name='публичная/приватная')),
                ('title', models.CharField(max_length=100, verbose_name='Название привычки')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность в минутах')),
                ('time_action', models.TimeField(max_length=25, verbose_name='Время, когда надо выполнить привычку')),
                ('action', models.CharField(max_length=100, verbose_name='Действие, которое надо сделать')),
                ('prize', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная-True/Полезная-False')),
                ('last_performed', models.DateField(blank=True, null=True, verbose_name='Дата последнего выполнения')),
                ('execution_interval_day', models.PositiveIntegerField(default=1, verbose_name='Интервал выполнения (дни)')),
                ('execution_interval_hour', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Интервал выполнения (часы)')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор привычки')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная с другой привычкой')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
